#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jsr311
Version  : 1.1.1
Release  : 3
URL      : https://github.com/javaee/jsr311/archive/jsr311-api-1.1.1.tar.gz
Source0  : https://github.com/javaee/jsr311/archive/jsr311-api-1.1.1.tar.gz
Source1  : https://repo.maven.apache.org/maven2/javax/ws/rs/jsr311-api/1.0/jsr311-api-1.0.jar
Source2  : https://repo.maven.apache.org/maven2/javax/ws/rs/jsr311-api/1.0/jsr311-api-1.0.pom
Source3  : https://repo.maven.apache.org/maven2/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
Source4  : https://repo.maven.apache.org/maven2/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CDDL-1.0
Requires: mvn-jsr311-data = %{version}-%{release}

%description
A REST-based API that empowers/enables developers to rapidly build Web
applications in Java that are characteristic of the best designed parts of the
Web.

%package data
Summary: data components for the mvn-jsr311 package.
Group: Data

%description data
data components for the mvn-jsr311 package.


%prep
%setup -q -n jsr311-jsr311-api-1.1.1

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.0/jsr311-api-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.0/jsr311-api-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.1.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.1.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.0/jsr311-api-1.0.jar
/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.0/jsr311-api-1.0.pom
/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
/usr/share/java/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.pom
